(() => {
  "use strict";
  const SUPABASE_URL = "https://ouyxhcmjwrqfmlqzuagj.supabase.co";
  const SUPABASE_KEY = "sb_publishable_NW2jRbkdYVN1IxLqeIv2mA_sltgk_QZ";
  const supabaseClient = window.supabase?.createClient(SUPABASE_URL, SUPABASE_KEY);
  let cloudEnabled = !!supabaseClient;
  let transactions = [];
  let activeType = "masuk", activeFilter = "semua", editingId = null, booting = true;
  let dashboardPeriod = "today", dashboardFilter = "keluar";
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  const rupiah = v => new Intl.NumberFormat("id-ID", {style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v)||0);
  const esc = v => String(v ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  function today(){const d=new Date(),l=new Date(d.getTime()-d.getTimezoneOffset()*60000);return l.toISOString().slice(0,10)}
  function newId(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}
  function normalize(x){return{id:x.id||newId(),d:x.d||x.transaction_date||today(),t:x.t==="keluar"||x.type==="keluar"?"keluar":"masuk",a:Number(x.a??x.amount)||0,c:String(x.c??x.category??"Lain-lain"),x:String(x.x??x.description??"")}}
  function toast(m){const e=$("#toast");if(!e)return;e.textContent=m;e.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove("show"),2800)}
  async function cloudLoad(){if(!supabaseClient)throw Error("Supabase client tidak tersedia");const{data,error}=await supabaseClient.from("transactions").select("id,type,amount,category,description,transaction_date,created_at").order("transaction_date",{ascending:false}).order("created_at",{ascending:false});if(error)throw error;return(data||[]).map(normalize)}
  async function cloudInsert(t){if(!supabaseClient)throw Error("Supabase tidak tersedia");const{error}=await supabaseClient.from("transactions").insert({id:t.id,type:t.t,amount:t.a,category:t.c,description:t.x,transaction_date:t.d});if(error)throw error}
  async function cloudUpdate(t){if(!supabaseClient)throw Error("Supabase tidak tersedia");const{error}=await supabaseClient.from("transactions").update({type:t.t,amount:t.a,category:t.c,description:t.x,transaction_date:t.d}).eq("id",t.id);if(error)throw error}
  async function cloudDelete(id){if(!supabaseClient)throw Error("Supabase tidak tersedia");const{error}=await supabaseClient.from("transactions").delete().eq("id",id);if(error)throw error}
  async function boot(){try{if(!supabaseClient)throw Error("Supabase client tidak tersedia");transactions=await cloudLoad();cloudEnabled=true;setStatus()}catch(e){console.error("Supabase boot error:",e);cloudEnabled=false;transactions=[];setStatus();toast(`❌ Database tidak terhubung: ${e.message||"cek Supabase URL, key, tabel, dan RLS"}`)}finally{booting=false;renderAll()}}
  function setStatus(){const b=document.querySelector(".brand small");if(b)b.textContent=cloudEnabled?"Telur · Cloud":"Telur · Database Offline"}
  function go(page){$$(".page").forEach(e=>e.classList.toggle("active",e.id===page));if(page==="dashboard")renderDashboard();if(page==="transactions")renderTransactions();if(location.hash!=="#"+page)history.replaceState(null,"","#"+page);window.scrollTo({top:0,behavior:"smooth"})}
  $$('[data-page]').forEach(e=>e.addEventListener("click",ev=>{ev.preventDefault();go(e.dataset.page);if($(".topbar")?.classList.contains("menu-open"))$("#navToggle")?.click()}));
  $$(".seg").forEach(b=>b.addEventListener("click",()=>{$$(".seg").forEach(x=>x.classList.remove("active"));b.classList.add("active");activeType=b.dataset.type}));
  const amount=$("#amount");
  amount?.addEventListener("input",()=>{const digits=amount.value.replace(/\D/g,"");amount.value=digits?Number(digits).toLocaleString("id-ID"):""});
  amount?.addEventListener("keydown",e=>{if(["e","E","+","-",".",","].includes(e.key))e.preventDefault()});
  if($("#date"))$("#date").value=today();
  $("#txForm")?.addEventListener("submit",async e=>{e.preventDefault();if(booting)return toast("⏳ Menghubungkan database...");if(!cloudEnabled)return toast("❌ Database offline. Transaksi tidak disimpan lokal.");const a=Number($("#amount").value.replace(/\D/g,"")),c=$("#category").value.trim()||"Lain-lain",x=$("#description").value.trim(),d=$("#date").value;if(!a)return toast("⚠ Isi nominal lebih dari 0");if(!d)return toast("⚠ Tanggal wajib diisi");const t={id:editingId||newId(),d:d,t:activeType,a:a,c:c,x:x},btn=e.submitter;if(btn)btn.disabled=true;try{if(editingId){const i=transactions.findIndex(z=>String(z.id)===String(editingId));if(i<0)throw Error("Transaksi tidak ditemukan");await cloudUpdate(t);transactions[i]=t;toast("✅ Transaksi diperbarui")}else{await cloudInsert(t);transactions.unshift(t);toast(`✅ ${activeType==="masuk"?"Uang masuk":"Uang keluar"} ${rupiah(a)} tersimpan`)}cancelEdit(false);renderAll()}catch(err){console.error(err);toast(`❌ Gagal menyimpan: ${err.message||"periksa Supabase"}`)}finally{if(btn)btn.disabled=false}});
  function startEdit(id){const t=transactions.find(z=>String(z.id)===String(id));if(!t)return;editingId=t.id;activeType=t.t;$$(".seg").forEach(b=>b.classList.toggle("active",b.dataset.type===activeType));$("#amount").value=Number(t.a).toLocaleString("id-ID");$("#category").value=t.c;$("#description").value=t.x;$("#date").value=t.d;const s=$("#txForm button[type=submit]");s.textContent="💾 Simpan Perubahan";let c=$("#cancelEdit");if(!c){c=document.createElement("button");c.type="button";c.id="cancelEdit";c.className="btn secondary";c.textContent="Batal Edit";c.onclick=()=>cancelEdit();s.parentElement.appendChild(c)}go("transactions");setTimeout(()=>$("#amount")?.focus(),100)}
  function cancelEdit(show=true){editingId=null;$("#txForm")?.reset();if($("#date"))$("#date").value=today();activeType="masuk";$$(".seg").forEach(b=>b.classList.toggle("active",b.dataset.type==="masuk"));const s=$("#txForm button[type=submit]");if(s)s.textContent="Simpan Transaksi";$("#cancelEdit")?.remove();if(show)toast("Edit dibatalkan")}
  $$(".filter").forEach(b=>b.addEventListener("click",()=>{$$(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");activeFilter=b.dataset.filter;renderTransactions()}));
  $("#search")?.addEventListener("input",renderTransactions);
  $$(".period").forEach(b=>b.addEventListener("click",()=>{$$(".period").forEach(x=>x.classList.remove("active"));b.classList.add("active");dashboardPeriod=b.dataset.period;renderDonut()}));
  $$(".cash-filter-btn").forEach(b=>b.addEventListener("click",()=>{$$(".cash-filter-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");dashboardFilter=b.dataset.chartFilter;renderDonut()}));
  $$('[data-quick-type]').forEach(b=>b.addEventListener("click",()=>{activeType=b.dataset.quickType;$$(".seg").forEach(x=>x.classList.toggle("active",x.dataset.type===activeType));setTimeout(()=>$("#amount")?.focus(),150)}));
  function renderTransactions(){const list=$("#txList");if(!list)return;const q=$("#search")?.value.trim().toLowerCase()||"";const data=transactions.filter(t=>(activeFilter==="semua"||t.t===activeFilter)&&(!q||[t.c,t.x,t.a].some(v=>String(v).toLowerCase().includes(q))));if(!data.length){list.innerHTML='<div class="empty">Belum ada transaksi.</div>';return}list.innerHTML=data.map(t=>{const i=t.t==="masuk",d=new Date(t.d+"T00:00:00").toLocaleDateString("id-ID",{day:"2-digit",month:"short",year:"numeric"});return`<div class="tx ${i?"in":"out"}"><div class="tx-icon">${i?"↗":"↘"}</div><div class="tx-main"><b>${esc(t.x||t.c)}</b><small>${esc(t.c)} • ${esc(d)}</small><span class="tx-type">${i?"UANG MASUK":"UANG KELUAR"}</span></div><div class="tx-amount ${i?"positive":"negative"}">${i?"+":"−"} ${rupiah(t.a)}</div><div class="tx-actions"><button type="button" class="edit" data-id="${esc(t.id)}">✏️</button><button type="button" class="delete" data-id="${esc(t.id)}">🗑️</button></div></div>`}).join("");$$('button.edit').forEach(b=>b.onclick=()=>startEdit(b.dataset.id));$$('button.delete').forEach(b=>b.onclick=async()=>{const id=b.dataset.id,t=transactions.find(z=>String(z.id)===String(id));if(!t||!confirm(`Hapus transaksi ${rupiah(t.a)}?`))return;try{await cloudDelete(id);transactions=transactions.filter(z=>String(z.id)!==String(id));renderAll();toast("🗑️ Transaksi dihapus")}catch(err){toast(`❌ Gagal menghapus: ${err.message}`)}})}
  function inPeriod(date){if(dashboardPeriod==="month"){const n=new Date(),d=new Date(date+"T00:00:00");return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()}if(dashboardPeriod==="7days"){const n=new Date(),s=new Date();s.setHours(0,0,0,0);s.setDate(s.getDate()-6);const d=new Date(date+"T00:00:00");return d>=s&&d<=n}return date===today()}
  function renderDashboard(){const n=new Date(),m=transactions.filter(t=>{const d=new Date(t.d+"T00:00:00");return d.getFullYear()===n.getFullYear()&&d.getMonth()===n.getMonth()}),inc=transactions.filter(t=>t.t==="masuk").reduce((s,t)=>s+t.a,0),out=transactions.filter(t=>t.t==="keluar").reduce((s,t)=>s+t.a,0),mi=m.filter(t=>t.t==="masuk").reduce((s,t)=>s+t.a,0),mo=m.filter(t=>t.t==="keluar").reduce((s,t)=>s+t.a,0);$("#balance")&&($("#balance").textContent=rupiah(inc-out));$("#income")&&($("#income").textContent=rupiah(mi));$("#expense")&&($("#expense").textContent=rupiah(mo));renderDonut()}
  function renderDonut(){const data=transactions.filter(t=>t.t===dashboardFilter&&inPeriod(t.d)),total=data.reduce((s,t)=>s+t.a,0),amount=$("#donutAmount"),label=$("#donutLabel"),chart=$("#donutChart");if(amount)amount.textContent=rupiah(total);if(label)label.textContent=dashboardFilter==="keluar"?"keluar":"masuk";if(chart)chart.style.setProperty("--donut-value",total?"100%":"0%");const box=$("#categoryChart");if(!box)return;const map={};data.forEach(t=>map[t.c]=(map[t.c]||0)+t.a);const en=Object.entries(map).sort((a,b)=>b[1]-a[1]);box.innerHTML=en.map(([c,v])=>`<div class="category-row"><div class="label"><span>${esc(c)}</span><b>${rupiah(v)}</b></div><div class="track"><div class="fill" style="width:${total?Math.max(4,v/total*100):0}%"></div></div></div>`).join("")}
  function renderAll(){renderTransactions();renderDashboard()}
  boot();
})();
